export const scoringConfig = {
  modelVersion: "heuristic-v1",
  trust: {
    baseScore: 50,
    officialSourceResolvedBonus: 24,
    missingOfficialPenalty: 20,
    companyLinkedBoardPenalty: 6,
    careersPageFallbackPenalty: 12,
    officialConfidence: {
      strongThreshold: 0.9,
      strongBonus: 10,
      mediumThreshold: 0.75,
      mediumBonus: 5,
      weakPenalty: 8,
    },
    canonicalSource: {
      companyCareersBonus: 16,
      trustedAtsBonus: 12,
      structuredPageBonus: 4,
      supplementalPenalty: 12,
    },
    multiActiveSourceBonus: 8,
    detailedDescriptionThreshold: 600,
    detailedDescriptionBonus: 5,
    sparseDescriptionThreshold: 120,
    sparseDescriptionPenalty: 8,
    endpointActiveBonus: 7,
    endpointInactivePenalty: 14,
    inconsistentTitlePenalty: 6,
    inconsistentLocationPenalty: 5,
    mirrorOnlyPenalty: 14,
    fuzzyClusterPenalty: 4,
    labels: {
      highConfidenceRealMin: 80,
      mediumConfidenceMin: 60,
      unverifiedSourceMin: 40,
    },
  },
  freshness: {
    baseScore: 70,
    firstSeen: {
      newestDays: 3,
      newestBonus: 16,
      recentDays: 7,
      recentBonus: 10,
      agingDays: 21,
      agingPenalty: 8,
      oldDays: 45,
      oldPenalty: 18,
    },
    lastSeen: {
      recentDays: 2,
      recentBonus: 10,
      staleDays: 14,
      stalePenalty: 12,
    },
    endpointActiveBonus: 8,
    endpointInactivePenalty: 22,
    missingOfficialPenalty: 10,
    companyLinkedBoardPenalty: 8,
    careersPageFallbackPenalty: 12,
    ambiguousClusterUnknownEndpointPenalty: 6,
    mirrorOnlyPenalty: 16,
    repostPenaltyThreshold: 3,
    repostPenalty: 18,
    inactiveJobPenalty: 18,
    labels: {
      newMin: 85,
      freshMin: 70,
      agingMin: 50,
      possiblyStaleMin: 35,
    },
  },
  priority: {
    salaryPresentBonus: 5,
    knownRemoteTypeBonus: 3,
    officialApplyBonus: 4,
    missingOfficialPenalty: 10,
    companyLinkedBoardPenalty: 20,
    careersPageFallbackPenalty: 28,
    agingFreshnessPenalty: 12,
    olderFreshRolePenalty: 12,
    ambiguousClusterPenalty: 8,
    suspiciousTrustPenalty: 18,
    stalePenalty: 15,
    highTrustNewBonus: 8,
    labels: {
      applyNowMin: 80,
      applySoonMin: 65,
      lowPriorityMin: 45,
    },
  },
} as const;

export type ScoringConfig = typeof scoringConfig;
